# see more details on
# https://pub.dev/packages/pedantic
# https://dart.dev/guides/language/analysis-options
# https://dart-lang.github.io/linter/lints/
#

include: package:effective_dart/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    avoid_returning_null_for_future: error
    avoid_void_async: error
    implementation_imports: info # todo: demonstrate warning level

linter:
  rules:
    - avoid_returning_null_for_future
    - avoid_void_async
