name: cocktailappmodelsconsumer
description: Example to show how can we import our models from outer package

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cocktailappmodels:
    path: ./../cocktail_app_models


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true