name: cocktailappmodels
description: There is first lesson in our course to get intro to Dart Lang & Flutter
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  http: ^0.12.2
  build_runner: ^1.0.0
  json_serializable: ^3.4.1


flutter:
